---
kind: pipeline
name: rust

steps:
  - name: clippy
    image: rust:latest
    environment:
      CARGO_TERM_COLOR: always
    commands:
    - rustup component add clippy
    - cargo clippy

  - name: rustfmt
    image: rust:latest
    environment:
      CARGO_TERM_COLOR: always
    commands:
      - rustup component add rustfmt
      - cargo fmt -- --check
---
kind: signature
hmac: 5eec1651270c767d1d3e554c47f31efb1481ef4b60a90e33e571955c23758c94

...
