[package]
name = "tf-viewer"
version = "0.1.0"
authors = ["daniel"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fitparser = "0.2.0"
sled = "0.34.4"
bincode = "1.3.1"
serde = { version = "1.0", features = ["derive"] }
url = "2.1.1"
chrono = "*"
actix-web = "3"
actix-identity = "0.3.1"
actix-service = "1.0.6"
actix-files = "0.4.0"
thiserror = "*"
askama = "0.10.3"
askama_actix = "0.11.0"
futures = "0.3.6"
