[package]
name = "tf-viewer"
version = "0.1.0"
authors = ["danielalvsaaker <daniel@nopemail.net>", "vidarandrebo"]
edition = "2018"
include = ["src/**/*", "LICENSE", "README.md", "templates", "static"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
jemalloc = ["jemallocator"]

[dependencies]
jemallocator = { version = "0.3.2", optional = true }
fitparser = "0.2.0"
sled = "0.34.6"
bincode = "1.3.1"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4.19"
actix-web = "3.3.2"
actix-identity = "0.3.1"
actix-service = "1.0.6"
actix-files = "0.4.1"
actix-multipart = "0.3.0"
url = "2.2.0"
rust-argon2 = { version = "0.8", default-features = false }
getrandom = "0.2"
anyhow = "1.0.35"
futures = "0.3.8"
askama = { version = "0.10.5", default-features = false }
askama_actix = "0.11.0"
plotly = "0.6.0"
staticmap = "0.2.0"
