[package]
name = "tf-viewer"
version = "0.1.1"
authors = ["danielalvsaaker <daniel@nopemail.net>", "vidarandrebo"]
edition = "2018"
include = ["src/**/*", "LICENSE", "README.md"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["embedded_static"]
jemalloc = ["jemallocator"]
embedded_static = ["lazy_static"]

[dependencies]
# web server etc.
actix-web = "3.3"
actix-identity = "0.3"
actix-files = "0.5"
actix-multipart = "0.3"
url = { version = "2.2", default-features = false }

# dynamic content generation
askama = { version = "0.10", default-features = false }
askama_actix = "0.11"
plotly = "0.6"
staticmap = "0.2"

# database, serializing/deserializing
sled = "0.34"
rmp-serde = "0.15"
serde = { version = "1.0", features = ["derive"] }

# activity related functions and types
fitparser = "0.3"
uom = { version = "0.31", default-features = false, features = ["si", "use_serde", "u16", "f64"] }

# password hashing, salt
rust-argon2 = { version = "0.8", default-features = false }
getrandom = "0.2"

# config
toml = "0.5"

# error handling
thiserror = "1.0"

# other
chrono = { version = "0.4", default-features = false }
futures = { version = "0.3", default-features = false }
regex = { version = "1.4", default-features = false }

# Dependency for embedded static content
lazy_static = { version = "1.4", optional = true }

# Optional allocator, highly recommended on musl systems
jemallocator = { version = "0.3.2", optional = true }
