[package]
name = "tf-viewer"
version = "0.1.1"
authors = ["danielalvsaaker <daniel@nopemail.net>", "vidarandrebo"]
edition = "2018"
include = ["src/**/*", "LICENSE", "README.md"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# web server etc.
actix-web = { version = "4.0.0-beta.8", default-features = false, features = ["compress-brotli"] }
actix-files = "0.6.0-beta.6"
serde = { version = "1", features = ["derive"] }

# error handling
thiserror = "1.0"

tf-models = { path = "tf-models" }
tf-database = { path = "tf-database" }
#tf-auth = { path = "tf-auth" }
tf-parse = { path = "tf-parse" }
nanoid = "*"

[target.'cfg(all(target_env = "musl", target_pointer_width = "64"))'.dependencies.jemallocator]
version = "0.3"
