[package]
name = "tf-viewer"
version = "0.1.1"
authors = ["danielalvsaaker <daniel@nopemail.net>", "vidarandrebo"]
edition = "2021"
include = ["src/**/*", "LICENSE", "README.md"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "crates/tf-auth",
    "crates/tf-parse",
    "crates/tf-database",
    "crates/tf-macro",
]

[dependencies]
# web server etc.
axum = { version = "*", features = ["headers"] }
tower-http = { version = "0.2", features = ["cors", "compression-full"] }
tokio = { version = "1", features = ["full", "macros", "rt-multi-thread"] }
serde = { version = "1", features = ["derive"] }

oxide-auth-axum = "0.1"
oxide-auth = "0.5"

# error handling
thiserror = "1.0"
bytes = "*"

tf-models = { path = "crates/tf-models" }
tf-macro = { path = "crates/tf-macro" }
tf-database = { path = "crates/tf-database" }
tf-auth = { path = "crates/tf-auth" }
tf-parse = { path = "crates/tf-parse" }

nanoid = "*"
moka = { version = "0.7", features = ["future"] }
staticmap = "*"
crc32fast = "*"

[patch.crates-io]
chrono = { git = "https://github.com/chronotope/chrono", default-features = false }

[profile.dev]
debug = 0

[profile.release]
incremental = true
