[package]
name = "tf-viewer"
version = "0.1.0"
authors = ["danielalvsaaker <daniel@nopemail.net>", "vidarandrebo"]
edition = "2018"
include = ["src/**/*", "LICENSE", "README.md", "templates", "static"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
jemalloc = ["jemallocator"]

[dependencies]
jemallocator = { version = "0.3.2", optional = true }
fitparser = "0.3"
sled = "0.34"
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", default-features = false }
actix-web = "3.3"
actix-identity = "0.3"
actix-files = "0.5"
actix-multipart = "0.3"
url = { version = "2.2", default-features = false }
rust-argon2 = { version = "0.8", default-features = false }
getrandom = "0.2"
thiserror = "1.0"
futures = { version = "0.3", default-features = false }
askama = { version = "0.10", default-features = false }
askama_actix = "0.11"
regex = { version = "1.4", default-features = false }
plotly = "0.6"
staticmap = "0.2"
toml = "0.5"
