[package]
name = "tf-viewer"
version = "0.1.1"
authors = ["danielalvsaaker <daniel@nopemail.net>", "vidarandrebo"]
edition = "2021"
include = ["src/**/*", "LICENSE", "README.md"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
resolver = "2"
members = [
    "tf-auth",
    "tf-parse",
    "tf-database",
    "tf-macro",
]

[dependencies]
# web server etc.
axum = "*"
tower-http = { version = "*", features = ["cors"] }
tokio = { version = "1", features = ["full", "macros", "rt-multi-thread"] }
serde = { version = "1", features = ["derive"] }

oxide-auth-axum = { git = "https://github.com/danielalvsaaker/oxide-auth" }
oxide-auth = { git = "https://github.com/danielalvsaaker/oxide-auth" }
axum-debug = "*"

# error handling
thiserror = "1.0"

tf-models = { path = "tf-models" }
tf-macro = { path = "tf-macro" }
tf-database = { path = "tf-database" }
tf-auth = { path = "tf-auth" }
tf-parse = { path = "tf-parse" }
nanoid = "*"
bytes = "*"

[patch.crates-io]
chrono = { git = "https://github.com/chronotope/chrono", default-features = false }
