[package]
name = "tf-graphql"
version = "0.1.1"
authors = ["danielalvsaaker <daniel@nopemail.net>", "vidarandrebo"]
edition = "2021"
include = ["src/**/*", "LICENSE", "README.md"]

[dependencies]
oxide-auth = "0.5"

# error handling
thiserror = "1.0"
bytes = "*"

tf-models = { path = "../tf-models", features = ["graphql"] }
tf-database = { path = "../tf-database" }
tf-auth = { path = "../tf-auth" }

nanoid = "*"

async-graphql = { version = "*" }
async-graphql-axum = "*"
