version: "3"
services:
  tf-viewer:
    container_name: tf-viewer
    image: danielalvsaaker/tf-viewer:latest
    build: .
    environment:
      - TZ=UTC
    volumes: 
      - ./data:/data
    ports:
      - "8080:8080"
