[package]
name = "tf-events"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap = "5.4"
tokio = { version = "1", features = ["sync", "rt"] }

tf-models = { path = "../tf-models" }
